"""empty message

Revision ID: 298f4ff4b4ba
Revises: bc48c3decf22
Create Date: 2021-05-02 10:58:03.598688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298f4ff4b4ba'
down_revision = 'bc48c3decf22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validator_item_mapping', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validator_item_mapping', 'task_id')
    # ### end Alembic commands ###
