"""empty message

Revision ID: 2d1bc0389a27
Revises: a42a5146bdf4
Create Date: 2021-04-12 22:56:20.149247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1bc0389a27'
down_revision = 'a42a5146bdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('reference', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'reference')
    # ### end Alembic commands ###
