"""empty message

Revision ID: 353becc4e388
Revises: 8c374dfec824
Create Date: 2021-04-06 17:11:06.591651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '353becc4e388'
down_revision = '8c374dfec824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validator_item_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_subtask_mapping')
    op.add_column('item', sa.Column('isInitialize', sa.Integer(), nullable=True))
    op.add_column('subtask', sa.Column('item_id', sa.Integer(), nullable=True))
    op.add_column('subtask', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('hasInitialize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'hasInitialize')
    op.drop_column('subtask', 'user_id')
    op.drop_column('subtask', 'item_id')
    op.drop_column('item', 'isInitialize')
    op.create_table('user_subtask_mapping',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subtask_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtask.id'], name='user_subtask_mapping_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_subtask_mapping_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('validator_item_mapping')
    # ### end Alembic commands ###
