"""empty message

Revision ID: 4b84c35106ef
Revises: 298f4ff4b4ba
Create Date: 2021-05-02 11:49:20.063454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b84c35106ef'
down_revision = '298f4ff4b4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'createTime')
    op.drop_column('task', 'timeDemand')
    op.drop_column('task', 'subtaskDemand')
    op.drop_column('task', 'teamDemand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('teamDemand', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('task', sa.Column('subtaskDemand', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('timeDemand', mysql.DATETIME(), nullable=True))
    op.add_column('task', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
