"""'给Task增加resultTYPE'

Revision ID: 56d5e2fdc691
Revises: 
Create Date: 2021-03-25 22:33:07.614918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d5e2fdc691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('resultFileType', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'resultFileType')
    # ### end Alembic commands ###
