"""empty message

Revision ID: 57698d162420
Revises: 06bbcd9900cb
Create Date: 2021-03-27 20:19:04.328468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57698d162420'
down_revision = '06bbcd9900cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['token'])
    op.add_column('user_subtask_mapping', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('user_subtask_mapping', sa.Column('usid', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subtask_mapping', 'usid')
    op.drop_column('user_subtask_mapping', 'status')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
