"""empty message

Revision ID: a42a5146bdf4
Revises: 15cc43b70bbb
Create Date: 2021-04-11 16:53:41.576490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a42a5146bdf4'
down_revision = '15cc43b70bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtask', 'user_id')
    op.add_column('user', sa.Column('subtasks', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subtasks')
    op.add_column('subtask', sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
