"""empty message

Revision ID: ab3aaced2c00
Revises: a32946425894
Create Date: 2021-05-24 19:29:39.537375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3aaced2c00'
down_revision = 'a32946425894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('outside_token', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('outside_token', 'user', ['outside_token'], unique=True)
    # ### end Alembic commands ###
