"""empty message

Revision ID: b2fc53842894
Revises: 4b84c35106ef
Create Date: 2021-05-05 19:35:55.518376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2fc53842894'
down_revision = '4b84c35106ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('task', 'token')
    op.add_column('user', sa.Column('inside_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('outside_token', sa.String(length=255), nullable=True))
    op.drop_index('token', table_name='user')
    op.create_unique_constraint(None, 'user', ['outside_token'])
    op.create_unique_constraint(None, 'user', ['inside_token'])
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('token', 'user', ['token'], unique=True)
    op.drop_column('user', 'outside_token')
    op.drop_column('user', 'inside_token')
    op.add_column('task', sa.Column('token', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
