"""empty message

Revision ID: bc48c3decf22
Revises: 2d1bc0389a27
Create Date: 2021-04-13 21:18:28.949609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc48c3decf22'
down_revision = '2d1bc0389a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('has_selected_supply', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'has_selected_supply')
    # ### end Alembic commands ###
