"""empty message

Revision ID: c35b52de1475
Revises: a829be26b238
Create Date: 2021-03-31 20:50:05.781465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c35b52de1475'
down_revision = 'a829be26b238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_subtask_mapping')
    op.add_column('item', sa.Column('field', sa.String(length=255), nullable=True))
    op.add_column('item', sa.Column('info_box', sa.TEXT(), nullable=True))
    op.add_column('item', sa.Column('intro', sa.TEXT(), nullable=True))
    op.add_column('item', sa.Column('original_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('relation', sa.TEXT(), nullable=True))
    op.add_column('item', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'task_id')
    op.drop_column('item', 'relation')
    op.drop_column('item', 'original_id')
    op.drop_column('item', 'intro')
    op.drop_column('item', 'info_box')
    op.drop_column('item', 'field')
    op.create_table('item_subtask_mapping',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subtask_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='item_subtask_mapping_ibfk_1'),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtask.id'], name='item_subtask_mapping_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
