"""empty message

Revision ID: d6f26de54e04
Revises: 57698d162420
Create Date: 2021-03-27 20:30:37.212153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6f26de54e04'
down_revision = '57698d162420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subtask_mapping', 'usid')
    op.drop_column('user_subtask_mapping', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subtask_mapping', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('user_subtask_mapping', sa.Column('usid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
