"""empty message

Revision ID: d762aa28e110
Revises: ff3f95c1f0c4
Create Date: 2021-05-24 17:50:16.848911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd762aa28e110'
down_revision = 'ff3f95c1f0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'outside_token',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'outside_token',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
